config/routes.rb
ShopifyEvents::Application.routes.draw do
  

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Resque::Server, :at => "/resque"
  
  
  match 'welcome' => 'home#welcome'
  match 'design' => 'home#design'
  
  match 'logout' => 'sessions#destroy'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end
  
  resources :events, controller: 'products'
  resources :products
  resources :variants
  resources :customers
  resources :orders
  resources :attendees
  
  #webhooks
  match ":class/:method/:shopid/webhook.json", :to => "webhook_events#create"
  
  root :to => 'home#index'
  

end

app/views/partials/_attendees.html.erb
<div class="well">
	<h3>ATTENDEES</h3>
	<br/>
	<div class="row-fluid">
		<% if @product.attendees.blank? %>
			<table class="table table-striped">
				<tr>
					<td><em>There are no event attendees for the <%= @product.title %>.</em></td>
				</tr>
				
			</table>
		<% else %>	
		<div class="table-products">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Phone</th>
				
			</tr>
		</thead>
		<tbody>
			<% @product.attendees.take(5).each do |i| %>
			<tr>
				<td><strong>
				<%= i.first_name  %> <%= i.last_name  %>
				</strong></td>
				<td><%= i.email  %>
					</td>
				<td><%= number_to_phone(i.phone)  %></td>
				
			</tr>
			<% end %>
		</tbody>
	</table>

</div>
<%= link_to "VIEW ALL", attendees_path(:id => @product), :class => "btn-flat default" %>

<% end %>
</div>


		
	</div>

app/views/partials/_event_stats.html.erb
<!-- upper main stats -->
<div id="main-stats">
	<div class="row-fluid stats-row">

		<div class="span4 stat">
			<div class="data">
				<span class="number"><%= @product.orders.count %></span>
				Registrations
			</div>
			<span class="date">Total</span>
		</div>
		<div class="span4 stat">
			<div class="data">
				<span class="number"><%= number_to_currency(@product.orders.sum(:total)) %></span>
				event revenue
			</div>
			<span class="date">This month</span>
		</div>
		<div class="span4 stat last">
			<div class="data">
				<span class="number"><%= @product.attendees.count %></span>
				confirmed attendees
			</div>
			<span class="date">last 30 days</span>
		</div>
	</div>
</div>
<!-- end upper main stats -->

app/views/partials/_morris_js.html.erb
<link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
	<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>

app/views/partials/_navbar.html.erb
<!-- navbar -->
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <a class="brand" href="index.html"><!-- ><img src="/images/ChorisM2M-Logo-White(black-matte.gif" width="171px" height="21px"> -->
            	niimbus EVENTS
            </a>

            <!-- shows same menu as sidebar but for mobile devices -->
            <button type="button" class="btn btn-navbar visible-phone" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>            
            <div class="nav-collapse collapse visible-phone mobile-menu">
                <!-- <ul class="nav">
                    <li class="active"><a href="index.html">Home</a></li>
                    <li><a href="chart-showcase.html">Charts</a></li>
                    <li><a href="user-list.html">Users</a></li>
                    <li><a href="form-showcase.html">Forms</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="icons.html">Icons</a></li>
                    <li><a href="calendar.html">Calendar</a></li>
                    <li><a href="tables.html">Tables</a></li>
                    <li><a href="ui-elements.html">UI Elements</a></li>
                </ul>-->
            </div>
            <!-- end navbar for mobile devices -->

            <ul class="nav pull-right">
                <% if shop_session %>
               <!--  <li class="hidden-phone">
                    <input class="search" type="text">
                </li>-->
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle hidden-phone" data-toggle="dropdown">
                        <%= session[:shopify].url %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Billing</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Send feedback</a></li>
                        <li><%= link_to "View Shopify", "http://#{session[:shopify].url}/admin/orders/", :target => "_blank" %></li>
                       
                    </ul>
                </li>
                	
                <li id="fat-menu" class="dropdown">
                    <li><%= link_to raw('<i class="logout"></i> Logout'), logout_path, :method => :delete %></li>
                </li>
                <% else %>
                	
                
                <% end %>
                
            </ul>            
        </div>
    </div>
    <!-- end navbar -->

app/views/partials/_orders.html.erb
<div class="well">
	<h3>REGISTRATIONS</h3>
	<br/>
	<div class="row-fluid">
		<% if @orders.blank? %>
			<table class="table table-striped">
				<tr>
					<td><em>There are no event registrations for the <%= @product.title %>.</em></td>
				</tr>
				
			</table>
		<% else %>		
		<div class="table-products">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Order Number</th>
				<th>Customer</th>
				<th>Quantity</th>
				<th>Total</th>
				<th>Status</th>
				<th></th>

			</tr>
		</thead>
		<tbody>
			<% @product.orders.take(5).each do |i| %>
			<tr>
				<td><strong>
				<%= i.order_number.upcase %>
				</strong></td>
				<td><%= link_to customer_path(i.customer) do %>
					<%= i.customer.first_name  %> <%= i.customer.last_name  %>
					<% end %>
					</td>
				<td><%= i.quantity  %></td>
				<td><%= number_to_currency(i.total) %></td>
				<td><%= i.status %></td>
				<td>
				<!--<ul class="actions">

					<li>
						<%= link_to edit_ticket_type_path(i) do %> 
							<i class="table-edit"></i>
						<% end %>
					</li>
					<li>
						<%= link_to image_tag("/img/ico-table-delete.png"),
                      			ticket_type_path(i), :method => :delete, 
                      			:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } 
                      			  %>
                      			
						
					</li>
				</ul> --></td>

			</tr>
			<% end %>
		</tbody>
	</table>

</div>
<%= link_to "VIEW ALL", orders_path(:id => @product), :class => "btn-flat default" %>
<% end %>
</div>

		
	</div>

app/views/partials/_registrations.html.erb
<div class="well">
	<h3>REGISTRATIONS</h3>
	<br/>
	<div class="row-fluid">
		
		<div class="table-products">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Order Number</th>
				<th>Customer</th>
				<th>Quantity</th>
				<th>Total</th>
				<th>Status</th>
				<th></th>

			</tr>
		</thead>
		<tbody>
			<% @event.registrations.take(5).each do |i| %>
			<tr>
				<td><strong>
				<%= i.order_number.upcase %>
				</strong></td>
				<td><%= link_to customer_path(i.customer) do %>
					<%= i.customer.first_name  %> <%= i.customer.last_name  %>
					<% end %>
					</td>
				<td><%= i.quantity  %></td>
				<td><%= number_to_currency(i.total) %></td>
				<td><%= i.status %></td>
				<td>
				<!--<ul class="actions">

					<li>
						<%= link_to edit_ticket_type_path(i) do %> 
							<i class="table-edit"></i>
						<% end %>
					</li>
					<li>
						<%= link_to image_tag("/img/ico-table-delete.png"),
                      			ticket_type_path(i), :method => :delete, 
                      			:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } 
                      			  %>
                      			
						
					</li>
				</ul> --></td>

			</tr>
			<% end %>
		</tbody>
	</table>

</div>
<%= link_to "VIEW ALL", registrations_path(:id => @event), :class => "btn-flat default" %>

</div>

		
	</div>

app/views/partials/_ticket_types.html.erb
<div class="well">
	<h3>TICKET TYPES</h3>
	<br/>
	
	<div class="row-fluid">
		<div id="bar-example" ></div>
		</div>
	
	<div class="row-fluid">

		<div class="table-products">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Name</th>
						<th>Capacity</th>
						<th>Price</th>
						<th></th>

					</tr>
				</thead>
				<tbody>
					<% @event.ticket_types.each do |i| %>
					<tr>
						<td><strong> <%= i.name.upcase %> </strong></td>
						<td><%= i.capacity  %></td>
						<td><%= number_to_currency(i.price) %></td>

						<td>
						<ul class="actions">

							<li>
								<%= link_to edit_ticket_type_path(i) do %>
								<i class="table-edit"></i>
								<% end %>
							</li>
							<li>
								<%= link_to image_tag("/img/ico-table-delete.png"),
								ticket_type_path(i), :method => :delete,
								:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }
%>

							</li>
						</ul></td>

					</tr>
					<% end %>
				</tbody>
			</table>

		</div>
	</div>

	<a href="#newModal" role="button" class="btn-flat gray" data-toggle="modal">+ NEW TICKET TYPE</a>
	
</div>

<%= render 'ticket_type_form' %>


<%= content_for :jsfooter do %>
		<%= render 'partials/morris_js' %>
<script>
	
	Morris.Bar({
  element: 'bar-example',
  data: [
  <% @event.ticket_types.each do |i| %>
    { y: '<%= i.name %>', a: <%= i.capacity %>, b: 90 },
    <% end %>
  ],
  xkey: 'y',
  ykeys: ['a', 'b'],
  labels: ['Capacity', 'Actual Attendance']
});
</script>
<% end %>

app/views/partials/_variants.html.erb
<div class="well">
	<h3>TICKET TYPES</h3>
	<br/>
	<% if @product.variants? %>
	<div class="row-fluid">
		<div id="bar-example" ></div>
		</div>
	
	<div class="row-fluid">

		<div class="table-products">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Name</th>
						<th>Capacity</th>
						<th>Price</th>
						<th>Status</th>
						<th></th>

					</tr>
				</thead>
				<tbody>
					<% @product.variants.each do |i| %>
					<tr>
						<td><strong> <%= i.name.upcase %> </strong></td>
						<td><%= i.capacity  %></td>
						<td><%= number_to_currency(i.price) %></td>
						<td>
							
							<% if i.active %>
				          		<span class="label label-success">Active</span>
				          <% else %>
				          		<span class="label label-info">Inactive</span>
				          <% end %>
							
							
						</td>
						<td>
						<ul class="actions">

							<li>
								<%= link_to edit_variant_path(i) do %>
								<i class="table-edit"></i>
								<% end %>
							</li>
							<li>
								<%= link_to image_tag("/img/ico-table-delete.png"),
								variant_path(i), :method => :delete,
								:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }
%>

							</li>
						</ul></td>

					</tr>
					<% end %>
				</tbody>
			</table>

		</div>
	</div>

	
	<% else %>
	<table class="table table-striped">
				<tr>
					<td><em>There are no ticket types for the <%= @product.title %>.</em></td>
				</tr>
				
			</table>
	<% end %>
	<a href="#newModal" role="button" class="btn-flat gray" data-toggle="modal">+ NEW TICKET TYPE</a>
</div>

<%= render 'variant_form' %>


<%= content_for :jsfooter do %>
		<%= render 'partials/morris_js' %>
<script>
<% if @product.variants? %>	
	Morris.Bar({
  element: 'bar-example',
  data: [
  <% @product.variants.each do |i| %>
    { y: '<%= i.name %>', a: <%= i.capacity %>, b: 90 },
    <% end %>
  ],
  xkey: 'y',
  ykeys: ['a', 'b'],
  labels: ['Capacity', 'Actual Attendance']
});
<% end %>
</script>
<% end %>