config/routes.rb
ShopifyEvents::Application.routes.draw do
  

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Resque::Server, :at => "/resque"
  
  
  match 'welcome' => 'home#welcome'
  match 'design' => 'home#design'
  
  match 'logout' => 'sessions#destroy'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end
  
  resources :events, controller: 'products'
  resources :products
  resources :variants
  resources :customers
  resources :orders
  resources :attendees
  
  #webhooks
  match ":class/:method/:shopid/webhook.json", :to => "webhook_events#create"
  
  root :to => 'home#index'
  

end

app/models/event.rb
class Event

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  include Mongoid::Multitenancy::Document
  
  field :method, type: String
  field :class, type: String
  field :body, type: String
  
  belongs_to :shop
  tenant(:shop)
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<br/>
<%= simple_form_for @event, :html => { :class => 'form-vertical well' } do |c| %>
  
 <div class="row-fluid">
  <div class="span5">
  	<h3>EVENT DETAILS</h3><br/>
  	<%= c.input :title, :required => true %>
  	<%= c.input :start_datetime, :required => true %> 
  	<%= c.input :end_datetime, :required => true %>
  	</div>
  	
  	
  	<div class="span5">
	  	<h3>VENUE DETAILS</h3> <br/>
	  	<%= c.input :venue_virtual, :as => :boolean %>
	  	<%= c.input :venue_street_address, :required => true %>
	  	<%= c.input :venue_secondary_address %> 
	  	<%= c.input :venue_city, :required => true %>
	  	<%= c.input :venue_state_province, :required => true %>
	  	<%= c.input :venue_country, :required => true %> 
  	</div>
  </div>
  <div class="row-fluid">
  	<hr/>
  	<div class="span12 ">
  	<h3>EVENT DESCRIPTION</h3> <br/>
	  	<%= c.input :body_html, :as => :text, :label => false, :input_html => { :cols => 900, :rows => 10, :style => "width: 600px;" } %>
	  	</div>
  	</div>
  		
  <div class="form-actions">
    <%= c.button :submit, :class => 'btn-flat primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn-flat inverse' %>
  </div>
  
  
  

<% end %>



<% content_for :jsfooter do %>


<%= javascript_include_tag "../mobiscroll-2.1/js/mobiscroll-2.1.custom.min.js"%>
<script>
	
	$(function(){
	    var now = new Date();
	
	    $('#event_start_datetime').scroller({
	        preset: 'datetime',
	        minDate: new Date(now.getFullYear(), now.getMonth(), now.getDate()),
	        theme: 'ios',
	        display: 'bottom',
	        mode: 'scroller'
	    });    
	
	    $('#show').click(function(){
	        $('#it').scroller('show'); 
	        return false;
	    });
	    $('#clear').click(function () {
	        $('#it').val('');
	        return false;
	    });
	});
	
	$(function(){
	    var now = new Date();
	
	    $('#event_end_datetime').scroller({
	        preset: 'datetime',
	        minDate: new Date(now.getFullYear(), now.getMonth(), now.getDate()),
	        theme: 'ios',
	        display: 'bottom',
	        mode: 'scroller'
	    });    
	
	    $('#show').click(function(){
	        $('#it').scroller('show'); 
	        return false;
	    });
	    $('#clear').click(function () {
	        $('#it').val('');
	        return false;
	    });
	});
	

</script>
 
 <script src="/bootstrap-wysihtml5-0.0.2/libs/js/wysihtml5-0.3.0_rc2.min.js"></script>
 <script src="/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.min.js"></script>
 
 <script>
 $('#event_body_html').wysihtml5({
	"font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
	"emphasis": true, //Italics, bold, etc. Default true
	"lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
	"html": true, //Button which allows you to edit the generated HTML. Default false
	"link": true, //Button to insert a link. Default true
	"image": true, //Button to insert an image. Default true,
	"color": false //Button to change color of font  
});
 </script>
 

	
	
<% end %>

<%= content_for :styles do %>

<link rel="stylesheet" type="text/css" href="/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.css"></link>

<% end %>

app/views/events/_ticket_type_form.html.erb
<!-- Modal -->
<div id="newModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">New <%= @event.title.upcase %> Ticket Type</h3>
  </div>
  <div class="modal-body">
  	
    <%= simple_form_for(@ticket_type) do |f| %>
	  <%= f.error_notification %>
	<div class="row-fluid">
	  
	  <div class="form-inputs span3">
	    <%= f.input :name, :required => true %>
	    <%= f.input :capacity, :required => true %>
	    <%= f.input :price, :required => true %>
	    <%= f.input :event_id, :as => :hidden, :input_html => { :value => @event.id } %>
	  </div>
	  
		<div class="span6 well pull-right alert-success">
		<strong>Capacity</strong> = How many total tickets are available at this price?
		</div>
	</div>  
	  
	  <div class="modal-footer">
	  	<button class="btn btn-flat gray" data-dismiss="modal" aria-hidden="true">Close</button>
	    <%= f.button :submit, :class => "btn btn-flat default" %>
	  </div>
	<% end %>
	
	
	
  </div>
 
</div>

app/views/events/_variant_form.html.erb
<!-- Modal -->
<div id="newModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">New <%= @event.title.upcase %> Ticket Type</h3>
  </div>
  <div class="modal-body">
  	
    <%= simple_form_for(@variant) do |f| %>
	  <%= f.error_notification %>
	<div class="row-fluid">
	  
	  <div class="form-inputs span3">
	    <%= f.input :name, :required => true %>
	    <%= f.input :capacity, :required => true %>
	    <%= f.input :price, :required => true %>
	    <%= f.input :event_id, :as => :hidden, :input_html => { :value => @event.id } %>
	  </div>
	  
		<div class="span6 well pull-right alert-success">
		<strong>Capacity</strong> = How many total tickets are available at this price?
		</div>
	</div>  
	  
	  <div class="modal-footer">
	  	<button class="btn btn-flat gray" data-dismiss="modal" aria-hidden="true">Close</button>
	    <%= f.button :submit, :class => "btn btn-flat default" %>
	  </div>
	<% end %>
	
	
	
  </div>
 
</div>

app/views/events/index.html.erb
<%- model_class = Event -%>

<h3>Events</h3>
	<div class="span10 pull-right">

		<%= link_to "+ NEW EVENT", new_event_path(), :class => 'btn-glow success pull-right' %>
	</div>
	
	

	<%- flash.each do |k, v| %>
	<div id="<%= k %>" class="alert alert-<%= k %>">
		<%= v %>
	</div>
	<% end %>

	
	 <div class="row-fluid ">
     
	 <ul class="nav nav-tabs" id="myTab">
	  <li><a href="#upcoming" data-toggle="tab">Upcoming</a></li>
	  <li><a href="#previous" data-toggle="tab">Previous</a></li>
	  <li><a href="#all" data-toggle="tab">All</a></li>
	  
	</ul>
	 
	<div class="tab-content">
		<div class="tab-pane" id="upcoming">
			<div class="table-products well">
				<% if @events_upcoming.blank? %>
			<table class="table table-striped">
				<tr>
					<td><em>There are no upcoming events.</em></td>
				</tr>
				
			</table>
		<% else %>	
		<table class="table table-hover">
		<thead>
			<tr>
				<th>Title</th>
				<th>Start</th>
				<th>End</th>
				<th></th>

			</tr>
		</thead>
		<tbody>
			<% @events_upcoming.each do |i| %>
			<tr>
				<td><strong><%= link_to event_path(i) do %>
				<%= i.title.upcase %>
				<% end %></strong></td>
				<td><%= i.start_datetime  %></td>
				<td><%= i.end_datetime %></td>

				<td>
				<ul class="actions">

					<li>
						<%= link_to edit_event_path(i) do %> 
							<i class="table-edit"></i>
						<% end %>
					</li>
					<li>
						<%= link_to edit_event_path(i) do %>
						<i class="table-delete"></i>
						<% end %>
					</li>
				</ul></td>

			</tr>
			<% end %>
		</tbody>
	</table>
	 <% end %>
		</div>
	 </div>
		<div class="tab-pane" id="previous">
			<div class="table-products well">
				<% if @events_previous.blank? %>
			<table class="table table-striped">
				<tr>
					<td><em>There are no previous events.</em></td>
				</tr>
				
			</table>
		<% else %>	
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Title</th>
				<th>Start</th>
				<th>End</th>
				<th></th>

			</tr>
		</thead>
		<tbody>
			<% @events_previous.each do |i| %>
			<tr>
				<td><strong><%= link_to event_path(i) do %>
				<%= i.title.upcase %>
				<% end %></strong></td>
				<td><%= i.start_datetime  %></td>
				<td><%= i.end_datetime %></td>

				<td>
				<ul class="actions">

					<li>
						<%= link_to edit_event_path(i) do %> 
							<i class="table-edit"></i>
						<% end %>
					</li>
					<li>
						<%= link_to edit_event_path(i) do %>
						<i class="table-delete"></i>
						<% end %>
					</li>
				</ul></td>

			</tr>
			<% end %>
		</tbody>
	</table>
	 <% end %>
		</div>
	 </div>
	  <div class="tab-pane" id="all">
	  	
	  	<div class="table-products well">
	  		<% if @events.blank? %>
			<table class="table table-striped">
				<tr>
					<td><em>There are no events.</em></td>
				</tr>
				
			</table>
		<% else %>	
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Title</th>
				<th>Start</th>
				<th>End</th>
				<th></th>

			</tr>
		</thead>
		<tbody>
			<% @events.each do |i| %>
			<tr>
				<td><strong><%= link_to event_path(i) do %>
				<%= i.title.upcase %>
				<% end %></strong></td>
				<td><%= i.start_datetime  %></td>
				<td><%= i.end_datetime %></td>

				<td>
				<ul class="actions">

					<li>
						<%= link_to edit_event_path(i) do %> 
							<i class="table-edit"></i>
						<% end %>
					</li>
					<li>
						<%= link_to edit_event_path(i) do %>
						<i class="table-delete"></i>
						<% end %>
					</li>
				</ul></td>

			</tr>
			<% end %>
		</tbody>
	</table>
	 <% end %>
		</div>
	  	
	  	
	  </div>
	</div>
	 
	<% content_for :jsfooter do %>
		 <script>
		 $(document).ready(function() {
		  $('#myTab a:first').tab('show');
		});
	  
		</script>
	
		
	<% end %>
	 
</div>