config/routes.rb
ShopifyEvents::Application.routes.draw do
  

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Resque::Server, :at => "/resque"
  
  
  match 'welcome' => 'home#welcome'
  match 'design' => 'home#design'
  
  match 'logout' => 'sessions#destroy'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end
  
  resources :events, controller: 'products'
  resources :products
  resources :variants
  resources :customers
  resources :orders
  resources :attendees
  
  #webhooks
  match ":class/:method/:shopid/webhook.json", :to => "webhook_events#create"
  
  root :to => 'home#index'
  

end

app/models/customer.rb
class Customer
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  include Mongoid::Multitenancy::Document
  include Mongoid::History::Trackable
  
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :shopify_id, type: String
  
  tenant(:shop)
  
  has_many :orders
  
  
  
  
  
  
  
  
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  
  around_filter :shopify_session
  
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.order_by([[:first_name, :asc], [:last_name, :desc]]).page params[:page]
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @attendee, :html => { :class => 'form-vertical well' } do |f| %>
  
	<div class="row-fluid">
	  <div class="span5">
		  <h3>ATTENDEE DETAILS</h3><br/>
		    <%= f.input :first_name %>
		    <%= f.input :last_name %>
		    <%= f.input :email %>
		    <%= f.input :phone %>
		  
		</div>
	
	<div class="span5">
	  	<h3>ADDRESS DETAILS</h3> <br/>
	  	<%= f.input :street_address %>
	  	<%= f.input :secondary_street_address %>
	  	<%= f.input :city %>
	  	<%= f.input :state_province %>
	  	<%= f.input :country %> 
  	
  	</div>
	</div>
	  <div class="form-actions">
	    <%= f.button :submit, :class => 'btn-flat primary' %>
    	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                attendee_path(@attendee), :class => 'btn-flat inverse' %>
	  </div>
	  
	  
	  
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
	<div class="row-fluid header">
                    <h3>Customers</h3>
                    
                </div>

                <!-- Users table -->
                <div class="row-fluid table-products well">
                	<% if @customers.blank? %>
						<table class="table table-striped">
							<tr>
								<td><em>There are no customers.</em></td>
							</tr>
							
						</table>
					<% else %>	
                    <table class="table table-hover ">
                        <thead>
                            <tr>
                                <th class="span4 sortable">
                                    Last Name
                                </th>
                                <th class="span4 sortable">
                                    First Name
                                </th>
                                <th class="span3 sortable">
                                    <span class="line"></span>Email
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        <!-- row -->
                        <% @customers.each do |customer| %>
                        <tr class="first">
                            <td><%= link_to customer_path(customer), :class => "name" do %>
                            		<%= customer.last_name %>
                            	<% end %>
                            </td>
                            <td><%= link_to customer_path(customer), :class => "name" do %>
                            		<%= customer.first_name %>
                            	<% end %>
                            </td>
                            <td><%= customer.email %></td>
						    
						</tr>
                        <% end %>
                        
                        </tbody>
                    </table>
                    <% end %>
                </div>
                <%= paginate @customers %>
                <!-- end users table -->
            

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
	<div class="container-fluid">
            <div id="pad-wrapper" class="user-profile">
                <!-- header -->
                <div class="row-fluid header">
                    <div class="span8">
                        <img src="/images/no-gravatar.png" class="avatar img-circle">
                        <h3 class="name"><%= @customer.first_name %> <%= @customer.last_name %></h3>
                    </div>
                    
                     <%= link_to t('.edit', :default => t("helpers.links.edit")),
		              edit_attendee_path(@customer), :class => 'btn-flat default pull-right' %>
                </div>

                <div class="row-fluid profile">
                    <!-- bio, new note & orders column -->
                    <div class="span9 bio">
                        <div class="profile-box">
                           
                            <h6>Event Registrations</h6>
                            <br>
                            <!-- recent orders table -->
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="span2">
                                            Order #
                                        </th>
                                        <th class="span2">
                                            Event
                                        </th>
                                        <th class="span3">
                                            <span class="line"></span>
                                            Quantity
                                        </th>
                                        <th class="span3">
                                            <span class="line"></span>
                                            Total
                                        </th>
                                        <th class="span3">
                                            <span class="line"></span>
                                           Status
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <!-- row -->
                                    <% @customer.registrations.each do |r| %>
                                    <tr class="first">
                                        <td>
                                            <%= r.order_number %>
                                        </td>
                                        <td>
                                            <%= link_to r.event.title, event_path(r.event) %>
                                        </td>
                                        <td>
                                           <%= r.quantity %>
                                        </td>
                                        <td>
                                            <%= number_to_currency(r.total) %>
                                        </td>
                                        <td>
                                           <%= r.status %>
                                        </td>
                                    </tr>
                                    <% end %>
                                    
                                </tbody>
                            </table>

                            <!-- new comment form 
                            <div class="span12 section comment">
                                <h6>Add a quick note</h6>
                                <p>Add a note about this user to keep a history of your interactions.</p>
                                <textarea></textarea>
                                <a href="#">Attach files</a>
                                <div class="span12 submit-box pull-right">
                                    <input type="submit" class="btn-glow primary" value="Add Note">
                                    <span>OR</span>
                                    <input type="reset" value="Cancel" class="reset">
                                </div>
                            </div>-->
                        </div>
                        
                    </div>

                    <!-- side address column -->
                    <div class="span3 address pull-right">
                        <h6>Address</h6>
                        <iframe width="300" height="133" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com.mx/?ie=UTF8&amp;t=m&amp;ll=19.715081,-155.071421&amp;spn=0.010746,0.025749&amp;z=14&amp;output=embed"></iframe>
                        <ul>
                            <li><%= @customer.address1 %></li>
                            <li><%= @customer.address2 %></li>
                            <li><%= @customer.zip %>, <%= @customer.province %>. <%= @customer.country %>,</li>
                            <li class="ico-li">
                                <i class="ico-phone"></i>
                                <%= @customer.phone %>
                            </li>
                             <li class="ico-li">
                                <i class="ico-mail"></i>
                                <a href="#"><%= @customer.email %></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


<% content_for :styles do %>

	<%= stylesheet_link_tag "/css/user-profile.css"%>
<% end %>