config/routes.rb
ShopifyEvents::Application.routes.draw do
  

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Resque::Server, :at => "/resque"
  
  
  match 'welcome' => 'home#welcome'
  match 'design' => 'home#design'
  
  match 'logout' => 'sessions#destroy'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end
  
  resources :events, controller: 'products'
  resources :products
  resources :variants
  resources :customers
  resources :orders
  resources :attendees
  
  #webhooks
  match ":class/:method/:shopid/webhook.json", :to => "webhook_events#create"
  
  root :to => 'home#index'
  

end

app/models/webhook_event.rb
class WebhookEvent
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  include Mongoid::Multitenancy::Document
  include Mongoid::History::Trackable
  
  field :body, type: String
  field :processed, type: Boolean
  
  tenant(:shop)
  
  
  track_history   :on => :all,       # track title and body fields only, default is :all
                  #:modifier_field => :modifier, # adds "belongs_to :modifier" to track who made the change, default is :modifier
                  #:modifier_field_inverse_of => :nil, # adds an ":inverse_of" option to the "belongs_to :modifier" relation, default is not set
                  :version_field => :version,   # adds "field :version, :type => Integer" to track current version, default is :version
                  :track_create   =>  false,    # track document creation, default is false
                  :track_update   =>  true,     # track document updates, default is true
                  :track_destroy  =>  false    # track document destruction, default is false
  
  
  after_create :addToResque
  
  private
  def addToResque
    puts "WEBHOOK EVENT ADDTORESQUE"
    Resque.enqueue_in(2.minutes, ShopifyWebhookWorker, self.id)
  end
  
  
  
end

app/controllers/webhook_events_controller.rb
class WebhookEventsController < ApplicationController
  
  #before_filter :verify_webhook, :except => 'verify_webhook' if Rails.env.production? # only extend in production
  
  def create
    
    if Shop.find(params["shopid"])
      
      @class = params["class"].classify.constantize 
      @instance = @class.where(shopify_id: params["id"])
    
      if !@instance.nil?
         @webhook_event = WebhookEvent.new(
          shop: Shop.find(params["shopid"]),
          processed: false,
          body: params
        )
        
      end
    end
    
    respond_to do |format|
      if @webhook_event.save
        #format.html { redirect_to @webhook_event, notice: 'Webhook event was successfully created.' }
        format.json { render json: @webhook_event, status: :created }
      else
        #format.html { render action: "new" }
        format.json { render json: @webhook_event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  
  private
  
  def verify_webhook
    data = request.body.read.to_s
    hmac_header = request.headers['HTTP_X_SHOPIFY_HMAC_SHA256']
    digest  = OpenSSL::Digest::Digest.new('sha256')
    calculated_hmac = Base64.encode64(OpenSSL::HMAC.digest(digest, ShopifyEvents::Application.config.shopify.secret, data)).strip
    unless calculated_hmac == hmac_header
      head :unauthorized
    end
    request.body.rewind
  end
  
  
  
  
  
  
end

app/helpers/webhook_events_helper.rb
module WebhookEventsHelper
end

app/views/webhook_events/_form.html.erb
<%= simple_form_for(@webhook_event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :method %>
    <%= f.input :class %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/webhook_events/edit.html.erb
<h1>Editing webhook_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @webhook_event %> |
<%= link_to 'Back', webhook_events_path %>

app/views/webhook_events/index.html.erb
<h1>Listing webhook_events</h1>

<table>
  <tr>
    <th>Method</th>
    <th>Class</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @webhook_events.each do |webhook_event| %>
  <tr>
    <td><%= webhook_event.method %></td>
    <td><%= webhook_event.class %></td>
    <td><%= webhook_event.body %></td>
    <td><%= link_to 'Show', webhook_event %></td>
    <td><%= link_to 'Edit', edit_webhook_event_path(webhook_event) %></td>
    <td><%= link_to 'Destroy', webhook_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Webhook event', new_webhook_event_path %>

app/views/webhook_events/new.html.erb
<h1>New webhook_event</h1>

<%= render 'form' %>

<%= link_to 'Back', webhook_events_path %>

app/views/webhook_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Method:</b>
  <%= @webhook_event.method %>
</p>

<p>
  <b>Class:</b>
  <%= @webhook_event.class %>
</p>

<p>
  <b>Body:</b>
  <%= @webhook_event.body %>
</p>


<%= link_to 'Edit', edit_webhook_event_path(@webhook_event) %> |
<%= link_to 'Back', webhook_events_path %>